/** @format */

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import Header from "../components/Header/Header";
import { HeroUIProvider } from "@heroui/system";
import { Providers } from "./providers";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

// Исправьте ваш RootLayout (app/layout.tsx)
export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" className="light" style={{ colorScheme: "light" }}>
			<body>
				<Providers themeProps={{ attribute: "class", defaultTheme: "light" }}>
					<Header></Header>
					{children}
				</Providers>
			</body>
		</html>
	);
}
